# -*- coding: utf-8 -*-
"""Trabajo-Practico-CalculoNum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvZTuDXvWPWkQEytn_e8aTf8VUVyn_6K
"""

students = [
    {"nombre": "José", "notas": [85, 90, 78, -10]},
    {"nombre": "Carlos", "notas": [88, 72, 94, 102]},
    {"nombre": "María", "notas": [95, 85, 87, "A++"]},
    {"nombre": "Rocío", "notas": ["A", "F", "B+", "C-"]},
    {"nombre": "Fabrizio", "notas": []}
]


def nota_valida(nota):
    return isinstance(nota, (int, float)) and 0 <= nota <= 100

for student in students:
    nombre = student["nombre"]
    notas = student["notas"]

    print("nombre: ",nombre, " su notas son: ",notas)


    for nota in notas:
      if nota_valida(nota):
            notas_validas.append(nota)
      else:
            notas_invalidas.append(nota)

    notas_validas = []
    notas_invalidas = []
    print("Notas válidas:", notas_validas)
    print("Notas inválidas:", notas_invalidas)